### ISSUE TITLE
Table Page

### ISSUE THREAD

**Issue by braddahboots** [DaDataDudes/HOME#12]
Reformat appearance and look into Griddle documentation for better layout. Currently tables are too messy http://griddlegriddle.github.io/Griddle/. 

Ideas: 
- Onload have better data values appear. 
- Fix scrolling lag

**Comment by warlokkz** [comment]
Formatted Griddle Tables with commit 9aab369fcb5e5c88524ae258bb5ffd3bc102fdb1 on dev branch.
